#page title
page_title                                : US Citizenship tracker                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6608959491                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : US Citizenship tracker                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : "Navigate your path to U.S. citizenship with ease using the US Citizenship Tracker. This app simplifies the process by helping you manage and track crucial dates, travel history, and eligibility requirements. With features like automatic itinerary import and real-time countdowns, you'll always be prepared for your next step towards citizenship. Stay organized and informed with personalized notifications and a user-friendly interface designed to take the stress out of your naturalization journey."

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
# your_name                                 : Pratyaksh Tyagi                                
# your_link                                 : https://pratyaksh.me                     
# your_city                                 : Arlington                                
# email_address                             : tyagipratyaksh@gmail.com
# facebook_username                         :                                           
# instagram_username                        : 
# twitter_username                          : 
github_username                           : pratyaksh123
# youtube_username                          : 


features:
  - title: Auto-import Itineraries
    description: Automatically import travel itineraries directly into your account by emailing them to a dedicated address.
    fontawesome_icon_name: envelope

  - title: Track Citizenship Eligibility
    description: Keep an eye on important dates and ensure you meet all necessary physical presence requirements for U.S. citizenship.
    fontawesome_icon_name: calendar-check

  - title: Manage Travel History
    description: Log and track your travels outside the U.S. to maintain accurate records for naturalization.
    fontawesome_icon_name: globe-americas

  - title: Secure and Private
    description: Your trip data is securely handled and automatically deleted after import. We prioritize privacy and never store or collect your travel information beyond what is necessary for immediate processing.
    fontawesome_icon_name: lock

  - title: Notifications and Reminders
    description: Receive timely notifications and reminders about upcoming deadlines and eligibility dates.
    fontawesome_icon_name: bell

  - title: Easy Setup
    description: Start tracking your journey to U.S. citizenship with a seamless and user-friendly setup process.
    fontawesome_icon_name: user-check


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
